# theme.toml template for a Hugo theme
# See https://github.com/gohugoio/hugoThemes#themetoml for an example

name = "Burwell"
license = "MIT"
licenselink = "https://github.com/Benjamin-Philip/burwell/blob/main/LICENSE"
description = "A theme inspired by (@benburwell) Ben Burwell's Personal Website."
homepage = "https://benjamin-philip.github.io/burwell"
tags = []
features = []
min_version = "0.41.0"

[author]
  name = "Benjamin Philip"
  homepage = "https://benjamin-philip.github.io/blog"

# If porting an existing theme
[original]
  name = "Ben Burwell's Personal Website"
  homepage = "https://www.benburwell.com/"
  repo = "https://github.com/benburwell/benburwell.github.io"
